name: Python application

on:
  push:
    branches: [ restruct ]
  pull_request:
    branches: [ restruct ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest ETC/ --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
